# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: PalYOH4F6D

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8085:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: PalYOH4F6D

  jaeger:
    image: jaegertracing/all-in-one:1.22
    restart: always
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:1.7
    ports:
      - '8086:8086'

#  influxdb_cli:
#    links:
#      - influxdb
#    image: quay.io/influxdb/influxdb:v2.0.3
#    # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
#    entrypoint: influx setup --bucket k6 -t mytoken -o myorg --username=admin --password=adminpassword --host=http://influxdb:8086 -f
#    # Wait for the influxd service in the influxdb container has fully bootstrapped before trying to setup an influxdb instance with the influxdb_cli service.
#    restart: on-failure:10
#    depends_on:
#      - influxdb